### PR TITLE
Add shutdown to RowEventListener

### PR DESCRIPTION
**Pull request by andrewkatz**
@trobrock

### CODE REVIEW

**Comment by andrewkatz** [comment]
Updating Romulan to gracefully handle disconnecting from RabbitMQ when the replicator is shut down.

**Comment by trobrock** [comment]
Does this improve something specifically?

**Review by trobrock — APPROVED** [review]

**Comment by andrewkatz** [comment]
Adding a trap to the replicator script so that it will call `RowServer#stop`, which will then call this new hook that's sent to the event listener so it can stop whatever it needs to, including the admin server and the connection to RabbitMQ.

**Comment by trobrock** [comment]
Ahh didn't know I didn't do this (https://github.com/greenbits/romulan/blob/spike-perf-refactor/scheduler.rb#L16) for the replicator too.

**Pull request merged**
